#!/bin/bash
set -euo pipefail #safety line

#aptimise.sh - written by bpm
#Generated by mkscript: 2018-02-28 14:51:46 GMT

VERSION=0.1.0

installed=${*:-$(apt-mark showmanual)}
#installed=$(apt list --manually-installed)

for i in $installed; do
    for j in $installed; do
        unset found;
        echo -n .
        if $(apt-cache rdepends -i $j | grep -q "^\s\+$i$" ); then
            found=$j;
            #printf '\nfound %s in %s\n' $i $j
            break
        fi
    done
    echo \n${found:-$i}
done
